---
title: "Simulation of Sugar Beet Growth"
author: "Agronomy and Crop Science Group, Kiel University"
date: "`r Sys.Date()`"
bibliography: bibliography.bibtex.bib
csl: european-journal-of-agronomy.csl
chunk_output_type: console
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
rm(list = ls(all.names = TRUE))

```

# The model

A process-oriented dynamic model was developed which runs on daily
time steps. Required external data inputs are the mean daily temperature
\[°C\], precipitation \[mm d^-1^\], global radiation \[W m^-2^\], wind
speed \[m s^-1^\], relative humidity \[%\] and values derived from these
like vapour pressure \[mbar\] and saturation deficit \[mbar\].
Temperature depended processes are calculated generally using an
effective temperature *(T~eff~)* \[°C\], which is the mean daily air
temperature \[°C\] *(T~air~)* minus a base temperature *(T~b~ = 3 °C)*,
which is the limit for growing processes in sugar beet [@milford1985analysis].

$$T_{eff}  = \left\{\begin{array}{2, 2}
T_{air} - T_{b} & |~~~T>0 \\ 
0 & |~T<30
\end{array}\right.$$

The model was implemented using an object oriented component library termed HUME
[@kage1999] on the basis of Embarcadero® Delphi®
2010 (Embarcadero Technologies, Inc., USA). The model is comprised of
submodels describing plant growth and development, soil water dynamics,
and evapotranspiration.

## Plant growth module

### Dry matter production

The simulation of plant growth is based on an approach using light use
efficiency *(LUE~PAR~)* \[g MJ^-1^\] to calculate dry matter production.
Leaf area index *(LAI)* \[m^2^ m^-2^\] is thereby used to calculate the
intercepted photosynthetic active radiation *(Q)* \[MJ m^-2^\]

$$Q=0.5\cdot {{R}_{global}}\cdot 1-{{e}^{-{{k}_{PAR}}\cdot LAI}}$$

where *R~global~* is the global radiation \[MJ m^-2^\] and *k~PAR~* the
extinction-coefficient for photosynthetic active radiation \[-\].
*k~PAR~* is assumed to be constant (Andrieu et al., 1997). The factor
0.5 reflects the assumption that roughly 50% of the incoming global
radiation is photosynthetic active radiation \[MJ m^-2^\] (Szeicz,
1974). The daily total dry matter growth rate \[g m^-2^ d^-1^\] is
calculated by multiplying the intercepted radiation *(Q)* with the
potenial light use efficiency for photosynthetic active radiation
*(LUE~PAR~)* \[g MJ^-1^\] and stress factors for drought stress
*(f~droughtLUE~)* \[-\] and for temperature *(f~tempLUE~)* \[-\].

$$\frac{dD{{M}_{total}}}{dt}=Q\cdot LU{{E}_{par}}\cdot {{f}_{droughtLUE}}\cdot {{f}_{tempLUE}}$$

*f~droughtLUE~* describes the reduction of dry matter production if
potential transpiration (T\~pot) \[mm d^-1^\] exceeds actual
transpiration (T\~act) \[mm d^-1^\].

$${{f}_{droughtLUE}}=\frac{{{T}_{act}}}{{{T}_{pot}}}$$

*ftempLUE* describes the reduction of dry matter production due to
suboptimal temperature. It follows a trapezoidal optimum function, which
can be described by 4 cardinal temperatures (T~b~ = minimum temperature
for dry matter production, T~2~ and T~3~ = lower an upper limit of the
optimal temperature range, T~4~ = maximum temperature). The values for
T~b~-T~4~ for the calculations of *ftempLUE* are obtained from the
literature and from experiment 1. Specification of the optimum
temperatures for growth processes in sugar beet varies within the
literature. Optimum temperature for leaf growth ranges between 19 °C
(Milford and Riley, 1980) and 24 °C (Terry, 1968) while that for taproot
growth was lower (12 °C (Milford and Riley 1980), 17 °C (Terry 1968) or
18 °C (Kenter et al., 2006)). Vandendriessche (2000) uses in his model a
temperature optimum from 10 °C to 25 °C for sugar beet assimilation. The
lower limit of the temperature optimum was parameterised using the data
of experiment 1 and resulted in T~2~ = 15.5 °C. As the upper limit of
the temperature optimum is unlikely to be reflected in the experimental
data a value of T~3~ = 25 °C was chosen to cover the mostly mentioned
optimum temperatures for taproot and leaf growth. T~4~ as upper limit
was set to 35 °C according to Vandendriessche (2000).

```{mermaid}

flowchart LR
  A(RUEpot) -.-> F
  C(ftempLUE) -.-> A
  D(fdroughtLUE) -.-> A
  E(Q) --> F{dWdt}
  F --> B[DM]
  
```

### Dry matter partitioning

Total dry matter *(DM~total~)* \[g m^-2^\] in the model is partitioned
into three plant components: root dry matter *(DM~root~)* \[g m^-2^\],
petiole dry matter *(DM~petiole~)* \[g m^-2^\] and leaf dry matter
*(DM~leaf~)* \[g m^-2^\]. *DM~root~* refers to the storage root of the
sugar beets.

$$D{{M}_{total}}=D{{M}_{root}}+D{{M}_{leaf}}+D{{M}_{petiole}}$$

In the model calculation the growth rate of *DM~total~* is allocated to
its components.

$$\frac{dD{{M}_{total}}}{dt}=\frac{dD{{M}_{root}}}{dt}+\frac{dD{{M}_{leaf}}}{dt}+\frac{dD{{M}_{petiole}}}{dt}$$

The growth rate of *DM~root~* is derived from the growth rate of
*DM~total~* using an allocation coefficient *f* \[-\] which in turn is
dependent on the amount of *DM~total~*

$$\frac{dD{{M}_{root}}}{dt}=\frac{dD{{M}_{total}}}{dt}\cdot (f+{{f}_{a}})$$

with

$$f={{({{f}_{a}}\cdot \ln (D{{M}_{total}})+{{f}_{b}})}_{{}}}$$

where *f~a~* and *f~b~* are empiric regression coefficients describing
slope and intercept of a linear regression of *f* on *DM~total~*. In
turn the daily growth rate of the shoot *(DM~shoot~)* can be calculated
by subtracting the daily growth rate of *DM~root~* from the daily growth
rate of *DM~total~* and *DM~dead~*, which is the senescent dry matter of
the leaves (see Eq. 16).

$$\frac{dD{{M}_{shoot}}}{dt}=\frac{dD{{M}_{total}}}{dt}-\frac{dD{{M}_{root}}}{dt}-\frac{dD{{M}_{dead}}}{dt}$$
To distribute the shoot dry matter into *DM~leaf~* and *DM~petiole~* an
allometric relationship between *DM~leaf~* and *DM~petiole~* is assumed.
The relative growth rates of *DM~leaf~* and *DM~petiole~* exhibit a
constant ratio leading to a linear function between the natural
logarithm of both fractions (Eq. 11).

$$\ln (D{{M}_{petiole}})={{f}_{la}}\cdot \ln (D{{M}_{leaf}})+{{f}_{lb}}$$

where *f~la~* and *f~lb~* \[-\] are regression coefficients. *f~leaf~*
can then be expressed as (Kage and Stützel, 1999b) The growth rates of
*DM~leaf~* and *DM~petiole~* are calculated from the growth rate of
*DM~shoot~* using *f~leaf~*.

$$\frac{dD{{M}_{leaf}}}{dt}={{f}_{leaf}}\cdot \frac{dD{{M}_{shoot}}}{dt}$$

and

$$\frac{dD{{M}_{petiole}}}{dt}=(1-{{f}_{leaf}})\cdot \frac{dD{{M}_{shoot}}}{dt}$$

$${{f}_{leaf}}=\frac{1}{1+{{e}^{{{f}_{lb}}}}\cdot {{f}_{la}}\cdot D{{M}_{leaf}}^{(f_{la}-1)}}$$

The sugar growth rate *(S)* is calculated according to Qi et al. (2005)
using a sugar partitioning coefficient *(SPC)*.

$$\frac{dS}{dt}=\frac{dD{{M}_{total}}}{dt}\cdot \left( \frac{SPC\cdot D{{M}_{total}}}{1+SPC\cdot D{{M}_{total}}} \right)$$

### Leaf area index calculation

To calculate the intercepted radiation the actual LAI is needed for Eq.
2. It is calculated from *DM~leaf~* using the specific leaf area *(SLA)*
\[cm^2^ g^-1^\].

$$LAI=\frac{D{{M}_{leaf}}\cdot SLA}{10000}$$

The *SLA* is calculated depending on three factors:

1.  Mean temperature over ten days *(T~mean~)* \[°C\],
2.  Mean PAR over ten days *(PAR~mean~)* \[MJ m^-2^\],
3.  Temperature sum *(T~Sum~)* \[°C\].

*T~sum~* is the accumulated *T~eff~* over time starting from sowing. The
parameters were obtained from parameterisation using data from
experiment 1. (Eq. 17) The dry matter production is initialised by the
calculation of the temperature depending leaf area index after emergence
*(LAI~e~)* \[m^2^ m^-2^\]. This starts if T~sum~ is greater than the
value of the growing degree-days needed for emergence *(T~em~)* \[°Cd\].
Hoffmann and Kluge-Severin (2011) estimated 100 to 130 °Cd to be
required for 50% field emergence of autumn and spring sown sugar beets,
whereas Guérif and Duke (1998) reported of 80--150 °Cd. We set *T~em~*
to 130 °Cd in our model. The determining factors for the exponential
early growth of *LAI~e~* are plant density *(SD)* \[plants m^-2^\], leaf
area per plant at emergence *(LAI~0~)* \[cm^2^ plant^-1^\], relative
growth rate of early canopy growth *(RGR~l~)* and T~sum~ and T~em~.

$$LAI_e=\frac{LAI_0 \cdot SD^{(RGR_{l} \cdot(T_{sum}-T_{em}))}}{10000}$$

The values for the *LAI~0~* and *RGR~l~* are used according to Guérif
and Duke (1998) while *LAI~crit~* was estimated from experiment 1. In
the start phase the *LAI* is replaced by *LAI~e~* in Eq. 2. The use of
*LAI~e~* is limited to a threshold *(LAI~crit~)* \[-\]. Exceeding this
threshold LAI growth is assumed to be not only temperature driven but
depending on assimilate availability. Therefore for *LAI* \> *LAI~crit~*
it is calculated according to Eq. 3. To take senescence processes in the
canopy into account an approach from Gabrielle et al. (1998) was used.
The maximum sustainable *LAI* *(LAI~susmax~)* \[m^2^ m^-2^\]) depending
on the incoming radiation is calculated as

$$LAI_{susmax}=\frac{1}{k} \cdot log(\frac{PAR_{mean}}{PAR_x \cdot f_{tempLAI}})$$

where *PAR~x~* is a threshold value for the radiation which is needed to
maintain leaf net assimilation positive. Below this value the bottom
leaves will start to become senescent. As the respiration is a process
depending on temperature, *PAR~x~* is modified by a temperature factor
*ftemp~LAI~*, which is based on a Q10 factor of 2 and a reference
temperature *(T~r~)* \[°C\] of 20 °C.

$$f_{tempLAI}=q_{10}^\frac{T_{air}-T_r}{10}$$

If *LAI* \> *LAI~susmax~* senescence due to low radiation occurs and the
daily senescence rate *LAI~s~* is calculated as

$$\frac {dLAI_s}{dt}=\,\left\{ \begin{align}
  & {LAI-LAI_{susmax} \cdot f_{sen}}\ \left| {LAI} \right.> LAI_{susmax} \\ 
 & 0~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ \ \ \ \ \ \ \ \ \ \left| {{T}_{eff}} \right.< LAI_{susmax} \\ 
\end{align} \right.\ $$

where *f~sen~* is a parameter describing the portion of *LAI* that is
reduced each day. As a reduction in the *LAI* due to senescence is
coupled with a reduction in *DM~shoot~* the amount of dead dry matter is
calculated *(DM~dead~)* \[g m^-2^\].

$$DM_{dead}=\frac {LAI_s}{SLA_{dead}} \cdot 10000$$

where *SLA~dead~* is the *SLA* of the senescent leaves.

### Evapotranspiration

The evapotranspiration module is based on the Penman-Monteith equation
(Monteith, 1973). This equation needs as input data global radiation \[W
m^-2^\], wind speed \[m s^-1^\], saturation deficit \[mbar\] and daily
mean temperature \[°C\] to calculate the potential evapotranspiration
*(ET~pot~)* \[mm d^-1^\]. These required data are obtained from the
model input weather data file. To calculate the aerodynamic resistance
of the crop *(r~a~)* \[s m^-1^\] and the canopy resistance *(r~c~)* \[s
m^-1^\] the crop height *(crop~height~)* \[m\] and the *LAI* are needed.
Both values are provided by the plant growth module. Potential
evapotranspiration is divided into potential evaporation *(E~pot~)* \[mm
d^-1^\] and potential transpiration *(T~pot~)* \[mm d^-1^\]) plus
interception *(I)* \[mm d^-1^\] according to the calculated amount of
radiation reaching the soil surface relative to the total global
radiation.

### Soil water

The soil water dynamics are simulated using a water content based
solution of the Richards-equation. The soil is divided in different
layers and for each layer the water content is calculated. *T~pot~* as
potential water uptake is distributed to the soil layers according to
the root length density *(RLD)* \[cm cm^-3^\] in each layer. It is
assumed, that the root length density decreases exponentially with soil
depth (Kage, 2000). The depth growth of the roots is linearly calculated
depending on *T~sum~* and a parameter *rd* \[cm d^-1^ °C\], which
describes the increase in rooting depth in relation to *T~sum~*. *rd*
was estimated using data presented by Brown and Biscoe (1985) and the
measured water content values from experiment 1. The maximum rooting
depth was assumed to be 150 cm. The root depth growth ceases at
temperatures \< 3 °C. The actual water uptake from the soil layer is
calculated from the potential uptake and a reduction function depending
on the water content.

### Additional components to simulate winter sugar beet

#### Leaf loss over winter

Winter sugar beets can lose their leaves and petioles over winter due to
frost, up to a total loss. According to an approach of Müller (2009),
negative mean daily temperatures \<-2° C are summed up *(TS~min~)*
\[°C\]. The rate of shoot dry matter loss is estimated from the existing
*DM~shoot~*, the changing rate of *TS~min~* and a factor for dry matter
decrease *(LPL)* \[-\].

$$\frac {dL_{Shoot}}{dt}=DM_{Shoot} \cdot \frac{dTS_{min}}{dt} \cdot LPL$$

The dry matter loss rate is then used to calculate the change rate of
*DM~shoot~*. The minimum value for *DM~shoot~* is 0.

$$\frac{dDM_{Shoot}}{dt}=\frac{dDM_{tot}}{dt}-\frac{dDM_{root}}{dt}-\frac{dL_{Shoot}}{dt}$$

A new initialization of the *LAI* is necessary, if *DM~leaf~* is 0.
Therefore in spring an initial LAI of 0.025 is assumed if the
temperature is \>*T~b~* and *LAI* \< 0.025, simulating a regrowth from
stored assimilates within the beet.

#### Vernalisation

Vernalisation was estimated using a modification of the model of Milford
et al. (2010). To be able to use daily weather data, the original model
working on an hourly basis was converted to a daily basis with mean
daily temperature. The daily vernalisation rate is calculated as a value
between 0 and 1 depending on *T~air~* (Fig. 1). The vernalisation values
of each day are added until the sum required for fully vernalising the
sugar beet was accomplished. Vernalising temperatures are commonly
assumed to range between 1--12 °C with an optimum between 6--8° C
(Jaggard et al., 1983; Milford et al., 2010). Data about the absolute
vernalisation requirement of sugar beet are still scarce. In a climate
chamber experiment with sugar beets, Mutasa-Gottgens et al. (2010) used
a temperature regime of 8 °C for 9 days, 6--8 °C for the following 18
days and a 7-day thermal buffer period at 15 °C as vernalisation (all in
one 32 days) whereas Crosthwaithe and Jenkins (1993) proposed 6--11 °C
with 8 hours of light for 3 month. Testing the vernalisation requirement
of Beta vulgaris spp. maritima from different populations across France
and Belgium Boudry et al. (2002) used 5--7 °C for 60 days to vernalise
the beets. We assumed temperatures of 5--7 °C for 60 days to be
sufficient to fully meet the vernalisation requirement of sugar beets.

#### Assumptions for non-bolting winter beet

As no non-bolting winter beet variety exists at present, it is assumed
that the growing phase in autumn/winter can be simulated according to
bolting winter beet. After reaching full vernalisation the beet follows
the growth pattern of conventional sugar beet in spring.
